node {
    def appDir = '/var/www/reactjs-app'
    
    stage('Clean Workspace') {
        deleteDir()
    }

    stage('Clone Repo') {
        echo 'Cloning repository...'
        git branch: 'main', url: 'https://github.com/rachnarajaka040/cicd-jenkins-aws.git'
    }

    stage('Deploy to Ec2') {
        echo 'Deploying to EC2...'
        sh """
            sudo mkdir -p ${appDir}
            sudo chown -R jenkins:jenkins ${appDir}

            # Chunki hum already login-signup-frontend folder ke andar hain, 
            # isliye hum current directory (./) se copy karenge.
            rsync -av --delete --exclude='.git' --exclude='node_modules' ./ ${appDir}/
            
            cd ${appDir}
            npm install
            npm run build --if-present

            sudo fuser -k 3000/tcp || true
            export JENKINS_NODE_COOKIE=dontKillMe
            nohup npm start > /dev/null 2>&1 &
        """
    }
}