node{
    def appDir='/var/www/reactjs-app'
    stage('Clean Workspace') {
        deleteDir()
    }
    stage('Clone Repo'){
        echo 'Cloning repository...'
        git (
            branch: 'main',
            url: 'https://github.com/rachnarajaka040/cicd-jenkins-aws.git'
        )
    }
    stage('Deploy to Ec2') {
        echo 'Deploying to EC2...'
        sh """
           sudo mkdir -p ${appDir}
           sudo chown -R 
           jenkins:jenkins ${appDir}

           rsync -av --delete 
           --exclude='.git'
            --exclude='node_modules'.
             / ${appDir}/
             cd ${appDir}
             sudo npm install
             sudo npm run build
             sudo fuser -k 3000/tcp ||
             true
             npm run start 

        """
    }
}


















pipeline {
    agent any

    environment {
        VERCEL_TOKEN = credentials('vercel_token')
    }

    stages {
        stage('Install') {
            steps {
                bat 'npm install'
            }
        }

        stage('Test') {
            steps {
                echo 'Skipping test'
            }
        }

        stage('Build') {
            steps {
                bat 'npm run build'
            }
        }

        stage('Deploy') {
            steps {
                bat "npx vercel --prod --yes --token=%VERCEL_TOKEN%"
            }
        }
    }
}